# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'PostgreSQL | Include OS-specific variables.'
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - 'default.yml'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'postgresql-configure'
    - 'postgresql-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PostgreSQL | Define PostgreSQL service name.'
  set_fact:
    postgresql_service_name: '{{ postgresql_default_service_name }}'
  when: 'not postgresql_service_name'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'postgresql-configure'
    - 'postgresql-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PostgreSQL | Define PostgreSQL packages.'
  set_fact:
    postgresql_packages: '{{ postgresql_default_packages }}'
  when: 'not postgresql_packages'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'postgresql-configure'
    - 'postgresql-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PostgreSQL | Define PostgreSQL bin directory.'
  set_fact:
    postgresql_bin_path: '{{ postgresql_default_bin_path }}'
  when: 'not postgresql_bin_path'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'postgresql-configure'
    - 'postgresql-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PostgreSQL | Define PostgreSQL config directory.'
  set_fact:
    postgresql_config_path: '{{ postgresql_default_config_path }}'
  when: 'not postgresql_config_path'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'postgresql-configure'
    - 'postgresql-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'PostgreSQL | Define PostgreSQL data directory.'
  set_fact:
    postgresql_data_path: '{{ postgresql_default_data_path }}'
  when: 'not postgresql_data_path'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'postgresql-configure'
    - 'postgresql-service'
    - 'package'
    - 'configure'
    - 'service'

- include_tasks: 'package.yml'
  tags:
    - 'postgresql'
    - 'postgresql-package'
    - 'package'

- include_tasks: 'configure.yml'
  tags:
    - 'postgresql'
    - 'postgresql-configure'
    - 'configure'

- include_tasks: 'service.yml'
  tags:
    - 'postgresql'
    - 'postgresql-service'
    - 'service'